### ISSUE TITLE
Cyclic dependency between server and konnect?

### ISSUE THREAD

**Issue by mithomas** [zokradonh/kopano-docker#129]
Service _kopano_server_ lists _kopano_konnect_ as a dependency and vice versa - while this does not pose a real issue on startup (even though I am not sure why), this is probably not intended.

**Comment by fbartels** [comment]
Hi @mithomas,

yes they are kind of symbiotic (at least in the configuration that is enforced through the compose file).

So for kopano_server to finally start it needs to get the discovery document from konnect. and to be able to use konnect kopano_server needs to be running so you can login.

Since depends_on in the  compose file is merely a "for this container to work, this other container needs to run" this should imho not cause any issues.

**Comment by mithomas** [comment]
Fine with me :-)
