### ISSUE TITLE
Figure out a way to run scripts after kopano-server container has started

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#15]
How to execute `kopano-cli --list-users` and `kopano-storeadm -h default: -P` after kopano-server has been started?
- `--list-users` should be run in regular intervals
- `kopano-storeadm` just needs to be run after startup, multiple executions do not harm

**Comment by zokradonh** [comment]
> * `--list-users` should be run in regular intervals

Why is this the case? To sync LDAP changes?
Then nearly all Kopano installations would need such regular task. Then it would be a good if Kopano itself would provide such an optional feature, isn't it?

If not, then we need a second process inside the container.
- The typical approach is to use supervisord and crond but I dislike it due to overkill.
- One could rely on stability of crond and simply start crond along in the start.sh. If it should crash anyhow then no one notices and the container is still up and running without crond.

**Comment by fbartels** [comment]
>> --list-users should be run in regular intervals
> Why is this the case? To sync LDAP changes?

`--list-users` may be a bad example in this case, `--sync` would be more appropriate. Actually there is an internal trigger in `kopano-server` (`sync_gab_realtime=yes` is actual the default configuration), but for performance reasons its advisable to deactivate it (this is actually not yet the case in this repo, will change that in a moment).

when that option is enabled every request of the gab will lead to a sync against the ldap,

> If not, then we need a second process inside the container.
> - The typical approach is to use supervisord

Yes, I was thinking of that as well. I have to see if dumb-init can be used for this as well.

**Comment by fbartels** [comment]
@zokradonh what do you think about the linked commit?

**Comment by zokradonh** [comment]
Good, I don't see any better solution. The most lightweight and stable solution for this kind of problem.
I really start to like the dockerize project.

I am not very familiar with the shell builtin `set`.

**Comment by fbartels** [comment]
`set` is just in there to let the script fail if any command in the script fails. For these two cases it's probably not even necessary (since no variables are involved).
