### ISSUE TITLE
config explanation to run behind traefik proxy

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#167]
Hi there, 

i want to contribute some condensed configuration insights to get this stack running behind an existing traefik ssl-proxy. I think a github wiki-page would be nice for this, but i don't know how to create a pull-request for a non-existing wiki-page. So please use this fork page as a kind of Pull-Request:
https://github.com/cguentherTUChemnitz/kopano-docker/wiki/Running-behind-traefik-reverse-proxy

**Comment by fbartels** [comment]
Hi @cguentherTUChemnitz,

thanks for opening this issue. I've skimmed through your linked page and this good from a technical perspective.

I am not quite sure about the wiki approach, though. Especially since at the moment it is not used for anything else. In the past I have already created the https://github.com/zokradonh/kopano-docker/tree/master/examples directory for some lightweight additional documentation (the rest of the docs are already in the README files). The only overhead of managing documentation inside of this git repo is imho that changes need to go through pull requests, whereas the github wiki is more freely to add.

What do you think, maybe we should rename the examples folder into docs and put your howto there? for the existing files I could even imagine putting them into subfolders with a small explanation for each of them.

**Comment by cguentherTUChemnitz** [comment]
I have no preference there on whow this explenation should be presented. the proposed method of placing the wiki-page as an readme file instead sounds also nice for me. In this way, it is also quite good linkable in the main readme file.

**Comment by fbartels** [comment]
Ok, then I would propose that you add a pull request to put your document into the examples/ folder.

**Comment by cguentherTUChemnitz** [comment]
https://github.com/zokradonh/kopano-docker/pull/170

**Comment by fbartels** [comment]
Thanks. I just merged it now.
