### ISSUE TITLE
portmapping discussion / network hardening

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#172]
I am trying to integrate this stack into my existing docker setup. The flexibility of providing system specific configuration via (service_specific).env file(s) and the docker-compose.override.yml fits the most use cases. The docker-compose.override.yml seems to help in all cases, where i want to override or add configuration to an container. Removing configuration from an container is not possible this way. Especially, when i want to get rid of some host-port mappings, i have to manually patch the main docker-compose.yml, which i want to avoid. A good use-case where this is necessary is https://github.com/zokradonh/kopano-docker/blob/master/examples/traefik-proxy-subdomain.md

I would like to see a discussion about two points:

1. Which of the host-mapped ports are really necessary? The services should be able to communicate directly through the docker networks they share using exposed ports, without mapping to the host. Getting rid of port-mappings

2. Which mapping should be able to be disabled? The setup i want to achieve is to use the kopano groupware on a dyndns-ed private machine, handling mail traffic via fetchmail and relay-host. Access for my clients like smartphone and desktop-software is treated only via active-sync / z-push. So i don't need any port-maps of the mail stack, because active-sync runs through my mapped traefik proxy in front of the kopano stack caddy-proxy. So do i see this right, that no host-port mapping is a viable solution for this scenario?

To preserve the current situation, but to be able to switch the portmapping without modifying the docker-compose.yml i want to present one possible solution:
https://github.com/zokradonh/kopano-docker/pull/171

**Comment by fbartels** [comment]
Yes, I was also briefly researching what ways there are to override the values for exposed ports, but out of the box this does not seem possible. So the only way to handle this is to put the port exposure into an extra file (like you have done in #171).

My fear with the approach in #171 is that this will increase the complexity of the whole setup to suite one (hopefully narrow) use case: using a different web proxy than kopano web.

In a way this reminded me of https://github.com/zokradonh/kopano-docker/issues/84

which port forwardings are really really needed?

I would say the only ports that you really need are port 25 to receive mails and port 443 for https. The rest is for added convenience or easier outside access (the port forwarding for kopano-ical is actually duplicated since this is also proxied in the web container).

**Comment by cguentherTUChemnitz** [comment]
Oh nice to see. Then i would need no port-mapping anymore by the kopano-stack, since 443 is proxied and receiving mails will be handled by fetchmail in my private setup ;)

> My fear with the approach in #171 is that this will increase the complexity of the whole setup to suite one (hopefully narrow) use case: using a different web proxy than kopano web.

I think this will enable also a flexible handling of which ports are mapped without modifying the main docker-compos.yml for other setups. This can be achieved by bulk-disable, via patching COMPOSE_FILE .env entry and enabling only specific ones, by passing them into the override.yml.

**Comment by fbartels** [comment]
#171 has been closed and the adapted #182 has been merged
