### ISSUE TITLE
userstores in national language

### ISSUE THREAD

**Issue by XtraLarge** [zokradonh/kopano-docker#248]
Hello,

nice work!!!, but I've a problem ....

The userstores are always be created in english (foldernames like "Inbox").
i've tried to change them to german, but no success.

Is there any way to set the to german, so folders are created like "Posteingang"?

**Comment by fbartels** [comment]
Hi @XtraLarge,

this can be configured through a setting. Please see https://documentation.kopano.io/kopanocore_administrator_manual/configure_kc_components.html?highlight=create%20store#configure-language-for-store-creation

Some notes if you want to open a pr to make this more clear.

- https://github.com/zokradonh/kopano-docker/blob/master/core/Dockerfile#L61-L62 can be removed now, since these options are not used any longer.
- to be able to create a store in a language the desired locale needs to exist in the container
  - build arg/env to select additional locales?
- an example for this could be added to docker-compose.yml (which uses en_US)
  - maybe this could even be put into .env and auto selected from the locale of the base system? (there should at least be a question about this similar to the timezone)

**Comment by fbartels** [comment]
related to https://github.com/zokradonh/kopano-docker/issues/100
