### ISSUE TITLE
Replace docker-proxy with Traefik (for ingress)

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#332]
When using docker-proxy external ips can otherwise not be seen, which interferes with rate limiting.

**Comment by theoneandonly-vector** [comment]
hey there, any news on this one? I'm not sure, but traefik should be able to "proxy" all tcp traffic, so maybe the SSL related difficulties can be fixed this way too..

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

due to other projects I have not yet done anything in this matter. In the end it should be more about providing documentation, than actual code changes.

If you want to work on that let me know. I'll be glad to review your docs/changes.

A while ago @cguentherTUChemnitz has already provided https://github.com/zokradonh/kopano-docker/blob/master/examples/traefik-proxy-subdomain.md, but that howto is more in the matter of replacing/augmenting the current "web" container, than using Traefik as a full blown ingress mechanism.

**Comment by theoneandonly-vector** [comment]
as traefik isn't compatible with imap and smtp, this isn't going to happen. when I find a truly open-source load-balancer/reverse-proxy with imap/SMTP-compatibility and Lets-Encrypt integration which already offers a docker-image, I'm gonna do it.

**Comment by cguentherTUChemnitz** [comment]
> as traefik isn't compatible with imap and smtp, this isn't going to happen. when I find a truly open-source load-balancer/reverse-proxy with imap/SMTP-compatibility and Lets-Encrypt integration which already offers a docker-image, I'm gonna do it.

@theoneandonly-vector 
Imho traefik should be able to handle such traffic very fine. Especially with the release of traefik >2.0  they are able to handle arbitrary tcp streams as a router configuration. https://docs.traefik.io/routing/routers/

Other guys are to place mailu smtp mailsever behind traefik when it stil was in 2.0 alpha stage and they got fixes to handle smtp stuff on their tcp routers. https://github.com/containous/traefik/issues/4875

Since traefik now is in 2.1 release i would assume that those fixes and merges are already present in the current releases.

**Comment by butonic** [comment]
AFAICT it should be possible to add a docker-compose.traefik.yml with the labels for traefik and completely replace caddy. We can do that in parallel with the caddy proxy, see how far we get and then decide how to proceed.
