### ISSUE TITLE
Replacing base-image with multi-stage build

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#34]
As far as I can see, we use https://github.com/zokradonh/kopano-docker/tree/master/base because of the necessary https://github.com/zokradonh/kopano-docker/blob/master/base/create-kopano-repo.sh file, which we are just using during the docker creation of the other images.

I'd rather suggest to create something like a multi-stage build (f.e. https://github.com/nupplaphil/kopano-ldap/blob/master/Dockerfile )

=> https://docs.docker.com/develop/develop-images/multistage-build/

- using/creating a builder for getting the right image ( = current `base` image) 
- inject the builder into the productive images (= `webapp` , `core` ) and copying the images

So we don't have any build-requiremented functions inside the productive image.

**Comment by fbartels** [comment]
Hi,

the idea behind the base image was to only manage the create repo script in one place (it is actually used in the core, webapp and z-push image by default).

I'm not sure how a multi stage build would help with that.

**Comment by nupplaphil** [comment]
The base image will not change. It's more like that (pseudo-code):
```Dockerfile
# Stage 1
FROM kopano:base AS builder
RUN set -ex && \
       get_image_stuff_with_custom_functions()

# Stage 2
FROM ubuntu:latest
COPY --from=builder /latest/downloaded/image /kopano
```

**Comment by fbartels** [comment]
Ok, I see what you're hinting at. Apart from "getting this script" out of the resulting image I do not see much of a (size) benefit in this. The packages you could then drop from the resulting images are apt-utils, curl, jq and maybe moreutils.

I am not quite sure if you have looked into what the script is doing. What it does is pulling packages from download.kopano.io.

**Comment by nupplaphil** [comment]
> Ok, I see what you're hinting at. Apart from "getting this script" out of the resulting I do not see much of a (size) benefit in this. The packages you could then drop from the resulting images are apt-utils, curl, jq and maybe moreutils.

Dropping unnecessary libraries out of docker images is always a good practice afaik :-)

> I am not quite sure if you have looked into what the script is doing. What it does is pulling packages from download.kopano.io.

I know. And the using containers are adding the package-directory as the kopano source path :-)

**Comment by zokradonh** [comment]
I don't see any real technical advantages of extracting those build helper binaries/scripts from productive image due to their small size.

Nevertheless I see the beauty of it, to have a "clean" productive image.

Currently we use kopano_base as common base image since it also installs some common used libraries. So we use it as shared Dockerfile. As far as I know this is the only way to avoid redundant Dockerfile code lines. So basing on ubuntu:latest like in your example would require duplicating the library installation on every component's Dockerfile.
And basing both build stages on kopano_base destroys all the beauty.

Furthermore if we do a supported build with subscription key, then there are no files to "COPY --from=builder". It will be directly installed by apt from official Kopano Repository.

So all in all it does not give us a real technical advantage and for some beauty we trade other ugliness in my opinion.

> Dropping unnecessary libraries out of docker images is always a good practice afaik :-)

Then we may could just uninstall them by using `apt`.

**Comment by nupplaphil** [comment]
Ok, that's of course reasonable .. 

I know from other docker-repositories that they are using something like an `update.sh` script, which possibly injects the necessary library-install-lines to a `Dockerfile.template` and moves them to the directories.

But they are mostly build for one docker image to maintain and this repo has more different docker images.

=> To be honest I don't know enough about Kopano (and especially the subscription functionallity) to have a valid argument anymore, so I close this issue :-)
