### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#342]
**Describe the bug**
After Updating everything I get the following errors:
webmail not working (502 Bad Gateway) & activesync not working.

log:
'''
kopano_zpush        | [Wed Feb 26 19:06:12.881117 2020] [php7:error] [pid 57] [client 172.23.0.2:51386] PHP Fatal error:  Uncaught Error: Call to undefined function mb_detect_encoding() in /usr/share/z-push/lib/utils/utils.php:1167\nStack trace:\n#0 /usr/share/z-push/lib/request/request.php(291): Utils::ConvertAuthorizationToUTF8('test.user...')\n#1 /usr/share/z-push/index.php(61): Request::ProcessHeaders()\n#2 {main}\n  thrown in /usr/share/z-push/lib/utils/utils.php on line 1167
'''

**To Reproduce**
use: docker-compose version 1.25.4, build 8d51620a
& Docker version 19.03.6, build 369ce74a3c
update using:
cd /opt/kopano-docker
git pull
docker-compose pull

**Expected behavior**
after stoping and restarting usign docker-compose up. everything starts up as before.

**Comment by theoneandonly-vector** [comment]
I reverted to a backup, but still have a copy of the failing VM for further investigation.

**Comment by fbartels** [comment]
Please provide the content of the bug issue template. Especially the following:

> **Additional context**
Add any other context about the problem here. Please check the [troubleshooting section](https://github.com/zokradonh/kopano-docker#troubleshooting) of the readme for additional details.

Bad gateway usually means that a container did not start and therefore cannot be reached from the proxy/web instance.

**Comment by fbartels** [comment]
i have reported the missing mbstring dependency upstream at https://jira.z-hub.io/browse/ZP-1541.

Will add a workaround for the time being.
