### ISSUE TITLE
how to create a multi-domain setup?

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#349]
hey there

anybody uses this with multiple domains?
As I can't find a way to add a 2nd domain, so I can use "https://mail.domain1.tld/webmail" and also "https://mail.domain2.tld/webmail"

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

this project currently supports only a single FQDN for the web frontend.

**Comment by mithomas** [comment]
I could imagine spinning up two separate webapp containers, one for each domain, configured against the same Kopano server; I suppose the overhead for this is bearable.

**Comment by fbartels** [comment]
@mithomas yes that would work for WebApp with the built-in login, but will fail/need additional changes when using OpenID Connect (Kopano Konnect) for signing in.

Similar will be the case for Meet and applications making use of the RestAPI (since request will likely be blocked because of cross domain communication)
