### ISSUE TITLE
Review supported build

### ISSUE THREAD

**Issue by zokradonh** [zokradonh/kopano-docker#429]
Building supported images has some troubles.

1. README points to non existent URL. There are no `files` packages for Debian_10.
```
KOPANO_WEBAPP_FILES_REPOSITORY_URL=https://download.kopano.io/supported/files:/final/Debian_10/
```
@fbartels  Do you know more about this?

2. `version.sh` does not support apt auth via `apt_auth.conf`. (I have implemented this today, will push to new branch as soon as I have a successful build)

I continue trying to build the supported build with most recent code and report problems.

**Comment by fbartels** [comment]
> @fbartels Do you know more about this?

Yes, I would have hoped that the WebApp team would have caught up by now, but there sadly has not been a final release since the general availability of Debian 10. There are packages however in https://download.kopano.io/supported/files%3A/pre-final/ which should work.

> version.sh does not support apt auth via apt_auth.conf. (I have implemented this today, will push to new branch as soon as I have a successful build)

that is one of the "drawbacks" of generally being whitelisted on that server 😅

I think it should be possible to pass the apt_auth files as a netrc one to curl. The files have the same format.

**Comment by zokradonh** [comment]
> I think it should be possible to pass the apt_auth files as a netrc one to curl. The files have the same format.

That sounds nice I will look into it.

**Comment by fbartels** [comment]
Just noticed that I actually already did change the setup.sh to use file from pre-final instead of final, since the latter was missing Debian 10 packages.

https://github.com/zokradonh/kopano-docker/commit/e99c524d4629899e02357bc573f0093d9fc74719

And with the PR merged for spamd the version.sh script now works as well, therefore I am closing here.
