### ISSUE TITLE
TCP communication instead of socket

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#48]
Currently we use sockets for communicating between the services.

Normally, in a micro-service environment, the services are loose coupled and therefore shouldn't share same volumes as far as possible.

f.e. I don't think that we can scale the services with the sockets, can we? Would it be possible to deploy more than one core? Is it even possible with the current kopano architecture?

[Edit] PS: I hope you I don't bug you with all my ideas/questions, if so, plz say and I will stop it!

**Comment by fbartels** [comment]
AFAIK it's fine in Swarm to share volumes since they can still be reached through the internal network.

If required in the desired deployment one can switch quite easily to TCP based sockets, since there are env variables for it (I just a few weeks ago switched everything over to file sockets, as they are more performant).

And yes, given the right configuration one can start multiple kopano-server containers (look up multi server configuration in the Kopano manual).

**Comment by nupplaphil** [comment]
I see... OK I'll now read through the whole kopano docs more carefully to avoid unnecessary topics anymore ;-)
