### ISSUE TITLE
If not demo env, do not import demo users

### ISSUE THREAD

**Issue by niklastojts** [zokradonh/kopano-docker#53]
Because setup.sh asks about wanted FQDN and allows to run "demo-ldap" container with other fqdn then kopano.demo, the file demo-users.ldif should be deleted/modified before docker-compose up.

Something like this in setup.sh:
```
value_default="kopano.demo"
read -p "FQDN to be used (for reverse proxy) [$value_default]: " new_value
FQDN=${new_value:-$value_default}

if [ "$FQDN" != "$value_default" ]; then
  rm -f "<path_to_dir/demo-ldap.ldif"
fi
```
I do understand that it is not so easy to just remove this file because your building your own ldap container.

**Comment by fbartels** [comment]
Hi @blinkiz ,

it would not work to delete the ldif, since the image has already been built and deleting would have no effect on that. I had discussed this in some issue with @nupplaphil already. For me personally this project is `an easy to replicate recipe to spin up a Kopano demo environment, which can (through modification of .env and possibly docker-compose.yml) also be used for production environments.` (hey it's even in the readme ;-) ) therefore I want to keep the demo users in the default docker-compose.

What I am totally fine with is a pr to establish another ldap image in this repo (so in addition to `ldap-demo` also a `ldap` image). You then move all the files of `ldap-demo` to `ldap` and in `ldap-demo` have a dockerfile that uses the result of `ldap` as a base and then adds the ldif with the demo users.

**Comment by nupplaphil** [comment]
Follow-Up discussion of #23 

@fbartels I would do:
- Adding `ldap` image like https://github.com/nupplaphil/kopano-ldap/blob/master/Dockerfile
- Adding the switch as @blinkiz said in `setup.sh`
  - if `kopano.demo`, use the ldap-demo image
  - if **not** `kopano.demò`, use the ldap image
- At the end, I can remove the `{{ LDAP_BASE_DN }}` in the `demo-user.ldiff` because there is only `kopano.demo` possible anymore ;-)

[edit] ok, that's exactly what you suggested in #23 , sorry I totally missed reading it the last time .. So at last we had the same thoughts ;-) ;-)

**Comment by fbartels** [comment]
Hmm.. I'd like to keep the dynamic domain for the demo ldif (plus the upstream change has just been added to the ldap image). What I could imagine is an explicit question to use the demo ldap or not. Based on the answer I'd imagine you can influence the actually started image in compose through an environment variable.
