### ISSUE TITLE
Official docker hub

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#55]
Currently, we're using @zokradonh repository for both github repo and docker hub.

I think to become more popular with the images, we should name the images the right way:
- `kopano/core` .. core server
- `kopano/webapp` ... webapp service
- `kopano/zpush` ... zpush service
- `kopano/ldap` ... LDAP server with kopano improvements (maybe with `kopano-ldap` extension when I'm finished ;-) )
- `kopano/webdav` ... kdav service

I think we could include the "work in progress" label to mark this hub as not finished yet. I believe this is, what the **Unofficial** label should suggest in this repo, shouldn't it? :-)

**Comment by fbartels** [comment]
Do you mean to tag the images with "work-in-progess" instead of "latest"?

The problem with hosting this git repo or the docker images in an organisation called "Kopano" is that regardless of how many times you write "unofficial" or "unsupported" people will just not read these hints. 

In the end, once this project has matured a bit, I do want to also push these images into a more official looking docker organisation. Nightly builds of master to hub.docker.com and release builds for Kopano customers into a private registry. This is ultimately why I did the Makefile, then building and tagging can easily carried out by our internal Jenkins.

But I still want to collect more feedback before going this step.
