### ISSUE TITLE
Misleading build.sh command synopsis regarding additional buildargs

### ISSUE THREAD

**Issue by mithomas** [zokradonh/kopano-docker#8]
While the command synopsis for build.sh reads:

```
# ./build.sh 
Usage: build.sh -c core|webapp [-s serial] [-b master|final|pre-final] [-p buildcontext] [-n networkname] [[-a buildarg] ...] [-i]
Example: build.sh -c core -s ABC123456789DEF -b final
-i   Do not use cache on docker build.
-b   If no branch is specified, 'master' will be built by default.
-p   If no buildcontext is specified, it will be built from git repository. Normally, you do not need to specify this.
-n   If no networkname is specified, it will create and use a network named 'buildproxy_net'.
-a   You can specify custom build args via e.g. -a KOPANO_CORE_REPOSITORY_URL=http://thisismy/url -a KOPANO_WEBAPP_REPOSITORY_URL=http://thisismy/url.
```

and thus claiming buildargs to be optional even in the example, running `# ./build.sh -c core -b final -n host` yields:

```
./build.sh: line 115: customBuildArgs[@]: unbound variable
```

This can be worked around by simply specifying a throwaway variable, e.g. `-a TEST`.

**Comment by zokradonh** [comment]
I cannot reproduce this.
`./build.sh -c core -b final -n host`
This line will not succeed since you cannot build from any branch without giving serial. 
build.sh requires either a serial so that it can access official Kopano repositories or you relocate the repository URLs with -a KOPANO_CORE_REPOSITORY_URL=http://... variables. E.g. to point to some repository created by kopano_version_watch project.

Nevertheless the error message `unbound variable` was not reproducible for me. I don't know how this error can occur since this variable is declared right in the first lines of the script and is therefore not unbound.

**Comment by mithomas** [comment]
Did you by any chance use a bash 4.4.x? I tried to reproduce it on bash 4.4.12 and did not succeed either - running the command in bash 4.3.30 however leads to the error.

I assume this has to do with this change introduced in bash 4.4.rc2:

> 3.  New Features in Bash
> 
> a.  Using ${a[@]} or ${a[*]} with an array without any assigned elements when
>     the nounset option is enabled no longer throws an unbound variable error.

(This makes this issue more and more irrelevant in the future; it can be from my point if view.)

**Comment by zokradonh** [comment]
Nice catch on this error btw! I am indeed using a new bash version.

I am currently changing again the build process and already pushed the new dockerfile some days ago. I need to change the build.sh a lot also or discard it completely, since build process is not that complicated anymore.

I didn't like the script anyway and the fact that sometimes a repository proxy container is needed just for building was also ugly in my opinion. Now I have found a good way to download community packages in an elegant way which allows direct building of this image by `docker build` again.

Thanks for contributing to my work and sorry for constantly changing the way it works.

**Comment by zokradonh** [comment]
I have now implemented an additional check for this error and tested with bash 4.3.30.
Should work now.

**Comment by fbartels** [comment]
obsoleted by Makefile and #14
